### ISSUE TITLE
Unfinished section in workshop guide - Frontend: 3.4.3

### ISSUE THREAD

**Issue by solomonbaez** [BcnRust/devbcn-workshop#16]
Under the App Effects section, immediately before the transition into the Film Modal subsection, there's a seemingly unfinished paragraph starting with "Sure, here's a revised version with a more formal tone: " just below the first code snippet on the page.

**Comment by piny4man** [comment]
My apologies, the unfinished paragraph was added by error during the final docs review. Thank you for pointing out.

**Comment by piny4man** [comment]
My apologies, the unfinished paragraph was added by error during the final docs review. Thank you for pointing out.
