### ISSUE TITLE
Unable to compile / shuttle run with database

### ISSUE THREAD

**Issue by f4bl3d** [BcnRust/devbcn-workshop#22]
Adding the line 
` #[shuttle_shared_db::Postgres()] pool: sqlx::PgPool,`
into 
`async fn actix_web(
 
) -> ShuttleActixWeb<impl FnOnce(&mut ServiceConfig) + Send + Clone + 'static> {
    let config = move |cfg: &mut ServiceConfig| {
        cfg.service(hello_world);
    };`
in main.rs in api > shuttle > src breaks the compile with:

no function or associated item named `new` found for struct `shuttle_shared_db::Postgres` in the current scope
items from traits can only be used if the trait is in scope rustc

**Comment by tomcodes** [comment]
I had the same issue as you, after some help on the BncRust discord server I managed to build the projetct:

* Downgrade the version of cargo-shuttle by running `cargo install cargo-shuttle --version 0.20.0`
* Downgrade the version of `shuttle-shared-db` in `api/shuttle/Cargo.toml` to `0.20.0`

Good luck!

**Comment by piny4man** [comment]
@f4bl3d @tomcodes We have updated the dependencies of the workshop and changed some of the code to match the new versions. Sorry for the late reply. Please give it a try if you can and let us know if you have any problems :pray:

**Comment by f4bl3d** [comment]
Great, thank you!
